--
-- PostgreSQL database dump
--

\restrict QCZqeTnvYrBRmq8VAuvwOHf5Ry3fMlocDteLY3hcSRpcoMGZSh4igrnSexcCqja

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-08-16 20:41:49

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 236 (class 1259 OID 49313)
-- Name: accounts_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_profile (
    id bigint NOT NULL,
    profile_image character varying(100),
    bio text,
    university character varying(150),
    major character varying(150),
    phone character varying(20),
    is_email_verified boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.accounts_profile OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 49312)
-- Name: accounts_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 54406)
-- Name: ai_assistant_chatmessage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ai_assistant_chatmessage (
    id bigint NOT NULL,
    role character varying(10) NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.ai_assistant_chatmessage OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 54405)
-- Name: ai_assistant_chatmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ai_assistant_chatmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_assistant_chatmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 49205)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 49204)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 49215)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 49214)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 49195)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 49194)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 49224)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 49243)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 49242)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 49223)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 49252)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 49251)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 51491)
-- Name: dashboard_activity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dashboard_activity (
    id bigint NOT NULL,
    action_type character varying(50) NOT NULL,
    description character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.dashboard_activity OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 51490)
-- Name: dashboard_activity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dashboard_activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dashboard_activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 49333)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 49332)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 49183)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 49182)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 49171)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 49170)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 49621)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 49374)
-- Name: notes_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notes_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    color character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.notes_category OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 49373)
-- Name: notes_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notes_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 49394)
-- Name: notes_note; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notes_note (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    summary text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint,
    user_id integer NOT NULL
);


ALTER TABLE public.notes_note OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 49393)
-- Name: notes_note_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notes_note ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_note_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 49408)
-- Name: notes_note_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notes_note_tags (
    id bigint NOT NULL,
    note_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.notes_note_tags OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 49407)
-- Name: notes_note_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notes_note_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_note_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 49385)
-- Name: notes_tag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notes_tag (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.notes_tag OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 49384)
-- Name: notes_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notes_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 49460)
-- Name: planner_task; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.planner_task (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    due_date timestamp with time zone,
    priority character varying(10) NOT NULL,
    status character varying(15) NOT NULL,
    is_completed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint,
    user_id integer NOT NULL
);


ALTER TABLE public.planner_task OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 49459)
-- Name: planner_task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.planner_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.planner_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 49518)
-- Name: quizzes_flashcard; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quizzes_flashcard (
    id bigint NOT NULL,
    front text NOT NULL,
    back text NOT NULL,
    known boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    source_note_id bigint,
    user_id integer NOT NULL,
    quiz_id bigint
);


ALTER TABLE public.quizzes_flashcard OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 49517)
-- Name: quizzes_flashcard_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quizzes_flashcard ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quizzes_flashcard_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 49504)
-- Name: quizzes_question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quizzes_question (
    id bigint NOT NULL,
    question_text text NOT NULL,
    options jsonb NOT NULL,
    correct_answer character varying(255) NOT NULL,
    user_answer character varying(255),
    explanation text,
    is_correct boolean,
    created_at timestamp with time zone NOT NULL,
    quiz_id bigint NOT NULL
);


ALTER TABLE public.quizzes_question OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 49503)
-- Name: quizzes_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quizzes_question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quizzes_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 49489)
-- Name: quizzes_quiz; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quizzes_quiz (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    score double precision NOT NULL,
    total_questions integer NOT NULL,
    correct_answers integer NOT NULL,
    completed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    source_note_id bigint,
    user_id integer NOT NULL
);


ALTER TABLE public.quizzes_quiz OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 49488)
-- Name: quizzes_quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quizzes_quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quizzes_quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 49532)
-- Name: quizzes_studysession; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quizzes_studysession (
    id bigint NOT NULL,
    subject character varying(150),
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone,
    duration_minutes integer NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL,
    category_id bigint,
    user_id integer NOT NULL
);


ALTER TABLE public.quizzes_studysession OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 49531)
-- Name: quizzes_studysession_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quizzes_studysession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quizzes_studysession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 49594)
-- Name: resources_resource; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.resources_resource (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    link character varying(500) NOT NULL,
    resource_type character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint,
    user_id integer NOT NULL
);


ALTER TABLE public.resources_resource OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 49593)
-- Name: resources_resource_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.resources_resource ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resources_resource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5267 (class 0 OID 49313)
-- Dependencies: 236
-- Data for Name: accounts_profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_profile (id, profile_image, bio, university, major, phone, is_email_verified, created_at, updated_at, user_id) FROM stdin;
2		\N	\N	\N	\N	f	2026-08-14 21:57:05.360231+03	2026-08-14 21:57:06.076204+03	2
3		\N	\N	\N	\N	f	2026-08-14 23:13:24.693929+03	2026-08-14 23:13:41.160573+03	3
1	profiles/WhatsApp_Image_2025-05-27_at_13.52.13_8f34a64e.jpg		MNU	\N	01002658457	f	2026-08-14 21:52:33.204274+03	2026-08-14 23:14:02.925916+03	1
\.


--
-- TOC entry 5294 (class 0 OID 54406)
-- Dependencies: 263
-- Data for Name: ai_assistant_chatmessage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ai_assistant_chatmessage (id, role, content, created_at, user_id) FROM stdin;
14	user	hi	2026-08-16 20:15:21.586827+03	1
15	ai	Hello! I'm your AI Study Coach. \n\nHow can I help you with your learning today? Whether you need help understanding a tough concept, planning a study schedule, practicing active recall, or preparing for an upcoming exam, just let me know what you are working on!	2026-08-16 20:15:40.708982+03	1
\.


--
-- TOC entry 5257 (class 0 OID 49205)
-- Dependencies: 226
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5259 (class 0 OID 49215)
-- Dependencies: 228
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5255 (class 0 OID 49195)
-- Dependencies: 224
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Profile	7	add_profile
26	Can change Profile	7	change_profile
27	Can delete Profile	7	delete_profile
28	Can view Profile	7	view_profile
29	Can add Task	8	add_task
30	Can change Task	8	change_task
31	Can delete Task	8	delete_task
32	Can view Task	8	view_task
33	Can add Category	9	add_category
34	Can change Category	9	change_category
35	Can delete Category	9	delete_category
36	Can view Category	9	view_category
37	Can add Tag	11	add_tag
38	Can change Tag	11	change_tag
39	Can delete Tag	11	delete_tag
40	Can view Tag	11	view_tag
41	Can add Note	10	add_note
42	Can change Note	10	change_note
43	Can delete Note	10	delete_note
44	Can view Note	10	view_note
45	Can add Resource	12	add_resource
46	Can change Resource	12	change_resource
47	Can delete Resource	12	delete_resource
48	Can view Resource	12	view_resource
49	Can add Quiz	15	add_quiz
50	Can change Quiz	15	change_quiz
51	Can delete Quiz	15	delete_quiz
52	Can view Quiz	15	view_quiz
53	Can add Question	14	add_question
54	Can change Question	14	change_question
55	Can delete Question	14	delete_question
56	Can view Question	14	view_question
57	Can add Flashcard	13	add_flashcard
58	Can change Flashcard	13	change_flashcard
59	Can delete Flashcard	13	delete_flashcard
60	Can view Flashcard	13	view_flashcard
61	Can add Study Session	16	add_studysession
62	Can change Study Session	16	change_studysession
63	Can delete Study Session	16	delete_studysession
64	Can view Study Session	16	view_studysession
65	Can add Activity	17	add_activity
66	Can change Activity	17	change_activity
67	Can delete Activity	17	delete_activity
68	Can view Activity	17	view_activity
69	Can add Chat Message	18	add_chatmessage
70	Can change Chat Message	18	change_chatmessage
71	Can delete Chat Message	18	delete_chatmessage
72	Can view Chat Message	18	view_chatmessage
\.


--
-- TOC entry 5261 (class 0 OID 49224)
-- Dependencies: 230
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1500000$LO6NmsQkGHluKjKB8WkuQe$jcLc+dy+YiBZE3MTA/c0BhrLbsQ6oOI6KHVVJjmsRiY=	\N	f	test_reset			test_reset@example.com	f	t	2026-08-14 21:57:05.358226+03
3	pbkdf2_sha256$1500000$lSvXXjJJgeTTUerX0Lqndy$LWgN+CEDgqXSPttiy1Rxn5JojDRV3TBrK80c5TITcGQ=	2026-08-14 23:13:41.1574+03	f	user			user@example.com	f	t	2026-08-14 23:13:23.895117+03
1	pbkdf2_sha256$1500000$xehvscLT3dasM1kZFJUpv0$Ir/9El1cyvOClPM+ZkCMfvJbJeXW+FEpnRoD/+3dMys=	2026-08-14 23:14:02.921647+03	f	mahmoud	mahmoud	sallam	sallammahmoud427@gmail.com	f	t	2026-08-14 21:52:32.324181+03
\.


--
-- TOC entry 5263 (class 0 OID 49243)
-- Dependencies: 232
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5265 (class 0 OID 49252)
-- Dependencies: 234
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5292 (class 0 OID 51491)
-- Dependencies: 261
-- Data for Name: dashboard_activity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dashboard_activity (id, action_type, description, created_at, user_id) FROM stdin;
1	TASK_CREATED	Created task 'physics task_1'	2026-08-14 22:25:30.774513+03	1
2	TASK_STATUS_TOGGLED	Task 'physics task_1' marked as completed	2026-08-14 22:25:34.631251+03	1
3	TASK_STATUS_TOGGLED	Task 'physics task_1' marked as pending	2026-08-14 22:25:35.134303+03	1
4	TASK_STATUS_TOGGLED	Task 'physics task_1' marked as completed	2026-08-14 22:25:35.917019+03	1
5	TASK_STATUS_TOGGLED	Task 'physics task_1' marked as pending	2026-08-14 22:25:39.059582+03	1
6	TASK_CREATED	Created task 'physics task_2'	2026-08-14 22:26:32.41436+03	1
7	TASK_STATUS_TOGGLED	Task 'physics task_2' marked as pending	2026-08-14 22:26:37.922321+03	1
8	TASK_STATUS_TOGGLED	Task 'physics task_1' marked as completed	2026-08-14 22:26:38.400162+03	1
9	TASK_STATUS_TOGGLED	Task 'physics task_1' marked as pending	2026-08-14 22:26:39.466126+03	1
10	TASK_CREATED	Created task 'physics task_3'	2026-08-14 22:27:00.048876+03	1
11	TASK_UPDATED	Updated task 'physics task_3'	2026-08-14 22:27:16.392593+03	1
12	TASK_STATUS_TOGGLED	Task 'physics task_1' marked as completed	2026-08-14 22:27:26.602807+03	1
13	TASK_CREATED	Created task 'physics task_4'	2026-08-14 22:27:50.885309+03	1
14	TASK_UPDATED	Updated task 'physics task_4'	2026-08-14 22:28:10.043113+03	1
15	TASK_STATUS_TOGGLED	Task 'physics task_4' marked as completed	2026-08-14 22:28:22.772339+03	1
16	TASK_CREATED	Created task 'electronics'	2026-08-14 22:29:36.391241+03	1
17	NOTE_CREATED	Created note 'mahmoud's note'	2026-08-14 23:12:10.315845+03	1
18	QUIZ_CREATED	Created quiz 'physics'	2026-08-15 01:23:03.097979+03	1
19	SESSION_STARTED	Started study session for 'General'	2026-08-16 19:26:31.235353+03	1
20	AI_CHAT	Asked AI: hi	2026-08-16 20:15:40.711593+03	1
\.


--
-- TOC entry 5269 (class 0 OID 49333)
-- Dependencies: 238
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 5253 (class 0 OID 49183)
-- Dependencies: 222
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	accounts	profile
8	planner	task
9	notes	category
10	notes	note
11	notes	tag
12	resources	resource
13	quizzes	flashcard
14	quizzes	question
15	quizzes	quiz
16	quizzes	studysession
17	dashboard	activity
18	ai_assistant	chatmessage
\.


--
-- TOC entry 5251 (class 0 OID 49171)
-- Dependencies: 220
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-14 21:37:36.995844+03
2	auth	0001_initial	2026-08-14 21:37:37.14065+03
3	accounts	0001_initial	2026-08-14 21:37:37.168236+03
4	admin	0001_initial	2026-08-14 21:37:37.210068+03
5	admin	0002_logentry_remove_auto_add	2026-08-14 21:37:37.21863+03
6	admin	0003_logentry_add_action_flag_choices	2026-08-14 21:37:37.229058+03
7	contenttypes	0002_remove_content_type_name	2026-08-14 21:37:37.25007+03
8	auth	0002_alter_permission_name_max_length	2026-08-14 21:37:37.261581+03
9	auth	0003_alter_user_email_max_length	2026-08-14 21:37:37.271705+03
10	auth	0004_alter_user_username_opts	2026-08-14 21:37:37.28567+03
11	auth	0005_alter_user_last_login_null	2026-08-14 21:37:37.295565+03
12	auth	0006_require_contenttypes_0002	2026-08-14 21:37:37.297034+03
13	auth	0007_alter_validators_add_error_messages	2026-08-14 21:37:37.306569+03
14	auth	0008_alter_user_username_max_length	2026-08-14 21:37:37.325451+03
15	auth	0009_alter_user_last_name_max_length	2026-08-14 21:37:37.342104+03
16	auth	0010_alter_group_name_max_length	2026-08-14 21:37:37.359529+03
17	auth	0011_update_proxy_permissions	2026-08-14 21:37:37.37473+03
18	auth	0012_alter_user_first_name_max_length	2026-08-14 21:37:37.386475+03
19	notes	0001_initial	2026-08-14 21:37:37.536457+03
20	planner	0001_initial	2026-08-14 21:37:37.588584+03
21	quizzes	0001_initial	2026-08-14 21:37:37.759848+03
22	resources	0001_initial	2026-08-14 21:37:37.818109+03
23	sessions	0001_initial	2026-08-14 21:37:37.839526+03
24	dashboard	0001_initial	2026-08-14 22:21:08.111762+03
25	ai_assistant	0001_initial	2026-08-15 00:16:23.895613+03
\.


--
-- TOC entry 5290 (class 0 OID 49621)
-- Dependencies: 259
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
4vi2mnv6ev3g2rrjuocz3zc6mvhvd5z7	.eJxVjDsOwyAQBe9CHSEvNhhSpvcZ0C67BCcRSP5UUe4eWXKRtG9m3ltF3LcS91WWOLO6KlCX340wPaUegB9Y702nVrdlJn0o-qSrnhrL63a6fwcF13LUIfgcUHpn0UMAAMvZh84xCHImtIMDMUacWBo9B4JkRpcHtJl66tTnC-joOEA:1wuyHy:_xrSzycw-meCbaX9vAqc3UhI97AliH-yNxL3ie5ITWQ	2026-08-28 23:14:02.928239+03
\.


--
-- TOC entry 5271 (class 0 OID 49374)
-- Dependencies: 240
-- Data for Name: notes_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notes_category (id, name, color, created_at, user_id) FROM stdin;
\.


--
-- TOC entry 5275 (class 0 OID 49394)
-- Dependencies: 244
-- Data for Name: notes_note; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notes_note (id, title, content, summary, created_at, updated_at, category_id, user_id) FROM stdin;
1	mahmoud's note	mahmoud	\N	2026-08-14 23:12:10.295965+03	2026-08-14 23:12:10.295975+03	\N	1
\.


--
-- TOC entry 5277 (class 0 OID 49408)
-- Dependencies: 246
-- Data for Name: notes_note_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notes_note_tags (id, note_id, tag_id) FROM stdin;
\.


--
-- TOC entry 5273 (class 0 OID 49385)
-- Dependencies: 242
-- Data for Name: notes_tag; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notes_tag (id, name, user_id) FROM stdin;
\.


--
-- TOC entry 5279 (class 0 OID 49460)
-- Dependencies: 248
-- Data for Name: planner_task; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.planner_task (id, title, description, due_date, priority, status, is_completed, created_at, updated_at, category_id, user_id) FROM stdin;
2	physics task_2		\N	MEDIUM	PENDING	f	2026-08-14 22:26:32.41172+03	2026-08-14 22:26:37.917606+03	\N	1
3	physics task_3		\N	HIGH	COMPLETED	t	2026-08-14 22:27:00.040731+03	2026-08-14 22:27:16.389066+03	\N	1
1	physics task_1		\N	MEDIUM	COMPLETED	t	2026-08-14 22:25:30.763747+03	2026-08-14 22:27:26.598532+03	\N	1
4	physics task_4		\N	LOW	COMPLETED	t	2026-08-14 22:27:50.881425+03	2026-08-14 22:28:22.767911+03	\N	1
5	electronics		2026-08-14 01:29:00+03	MEDIUM	PENDING	f	2026-08-14 22:29:36.387037+03	2026-08-14 22:29:36.387045+03	\N	1
\.


--
-- TOC entry 5285 (class 0 OID 49518)
-- Dependencies: 254
-- Data for Name: quizzes_flashcard; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quizzes_flashcard (id, front, back, known, created_at, source_note_id, user_id, quiz_id) FROM stdin;
\.


--
-- TOC entry 5283 (class 0 OID 49504)
-- Dependencies: 252
-- Data for Name: quizzes_question; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quizzes_question (id, question_text, options, correct_answer, user_answer, explanation, is_correct, created_at, quiz_id) FROM stdin;
\.


--
-- TOC entry 5281 (class 0 OID 49489)
-- Dependencies: 250
-- Data for Name: quizzes_quiz; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quizzes_quiz (id, title, score, total_questions, correct_answers, completed, created_at, updated_at, source_note_id, user_id) FROM stdin;
1	physics	0	0	0	f	2026-08-15 01:23:03.067686+03	2026-08-15 01:23:03.067694+03	1	1
\.


--
-- TOC entry 5287 (class 0 OID 49532)
-- Dependencies: 256
-- Data for Name: quizzes_studysession; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quizzes_studysession (id, subject, start_time, end_time, duration_minutes, notes, created_at, category_id, user_id) FROM stdin;
1	\N	2026-08-16 19:26:30.900393+03	\N	0		2026-08-16 19:26:30.902279+03	\N	1
\.


--
-- TOC entry 5289 (class 0 OID 49594)
-- Dependencies: 258
-- Data for Name: resources_resource; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.resources_resource (id, title, description, link, resource_type, created_at, updated_at, category_id, user_id) FROM stdin;
\.


--
-- TOC entry 5300 (class 0 OID 0)
-- Dependencies: 235
-- Name: accounts_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_profile_id_seq', 3, true);


--
-- TOC entry 5301 (class 0 OID 0)
-- Dependencies: 262
-- Name: ai_assistant_chatmessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ai_assistant_chatmessage_id_seq', 15, true);


--
-- TOC entry 5302 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5303 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5304 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- TOC entry 5305 (class 0 OID 0)
-- Dependencies: 231
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- TOC entry 5306 (class 0 OID 0)
-- Dependencies: 229
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- TOC entry 5307 (class 0 OID 0)
-- Dependencies: 233
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5308 (class 0 OID 0)
-- Dependencies: 260
-- Name: dashboard_activity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dashboard_activity_id_seq', 20, true);


--
-- TOC entry 5309 (class 0 OID 0)
-- Dependencies: 237
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5310 (class 0 OID 0)
-- Dependencies: 221
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- TOC entry 5311 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- TOC entry 5312 (class 0 OID 0)
-- Dependencies: 239
-- Name: notes_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notes_category_id_seq', 1, false);


--
-- TOC entry 5313 (class 0 OID 0)
-- Dependencies: 243
-- Name: notes_note_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notes_note_id_seq', 1, true);


--
-- TOC entry 5314 (class 0 OID 0)
-- Dependencies: 245
-- Name: notes_note_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notes_note_tags_id_seq', 1, false);


--
-- TOC entry 5315 (class 0 OID 0)
-- Dependencies: 241
-- Name: notes_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notes_tag_id_seq', 1, false);


--
-- TOC entry 5316 (class 0 OID 0)
-- Dependencies: 247
-- Name: planner_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.planner_task_id_seq', 5, true);


--
-- TOC entry 5317 (class 0 OID 0)
-- Dependencies: 253
-- Name: quizzes_flashcard_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quizzes_flashcard_id_seq', 1, false);


--
-- TOC entry 5318 (class 0 OID 0)
-- Dependencies: 251
-- Name: quizzes_question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quizzes_question_id_seq', 1, false);


--
-- TOC entry 5319 (class 0 OID 0)
-- Dependencies: 249
-- Name: quizzes_quiz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quizzes_quiz_id_seq', 1, true);


--
-- TOC entry 5320 (class 0 OID 0)
-- Dependencies: 255
-- Name: quizzes_studysession_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quizzes_studysession_id_seq', 1, true);


--
-- TOC entry 5321 (class 0 OID 0)
-- Dependencies: 257
-- Name: resources_resource_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.resources_resource_id_seq', 1, false);


--
-- TOC entry 5006 (class 2606 OID 49324)
-- Name: accounts_profile accounts_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_pkey PRIMARY KEY (id);


--
-- TOC entry 5008 (class 2606 OID 49326)
-- Name: accounts_profile accounts_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_key UNIQUE (user_id);


--
-- TOC entry 5071 (class 2606 OID 54417)
-- Name: ai_assistant_chatmessage ai_assistant_chatmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_assistant_chatmessage
    ADD CONSTRAINT ai_assistant_chatmessage_pkey PRIMARY KEY (id);


--
-- TOC entry 4979 (class 2606 OID 49369)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4984 (class 2606 OID 49270)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4987 (class 2606 OID 49222)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4981 (class 2606 OID 49211)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4974 (class 2606 OID 49261)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4976 (class 2606 OID 49203)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4995 (class 2606 OID 49250)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4998 (class 2606 OID 49285)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4989 (class 2606 OID 49239)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 5001 (class 2606 OID 49259)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5004 (class 2606 OID 49299)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4992 (class 2606 OID 49362)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 5067 (class 2606 OID 51500)
-- Name: dashboard_activity dashboard_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dashboard_activity
    ADD CONSTRAINT dashboard_activity_pkey PRIMARY KEY (id);


--
-- TOC entry 5011 (class 2606 OID 49346)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4969 (class 2606 OID 49193)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4971 (class 2606 OID 49191)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4967 (class 2606 OID 49181)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5063 (class 2606 OID 49630)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 5014 (class 2606 OID 49383)
-- Name: notes_category notes_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_category
    ADD CONSTRAINT notes_category_pkey PRIMARY KEY (id);


--
-- TOC entry 5017 (class 2606 OID 49417)
-- Name: notes_category notes_category_user_id_name_70a6122e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_category
    ADD CONSTRAINT notes_category_user_id_name_70a6122e_uniq UNIQUE (user_id, name);


--
-- TOC entry 5025 (class 2606 OID 49406)
-- Name: notes_note notes_note_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_note
    ADD CONSTRAINT notes_note_pkey PRIMARY KEY (id);


--
-- TOC entry 5030 (class 2606 OID 49446)
-- Name: notes_note_tags notes_note_tags_note_id_tag_id_e85f93da_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_note_tags
    ADD CONSTRAINT notes_note_tags_note_id_tag_id_e85f93da_uniq UNIQUE (note_id, tag_id);


--
-- TOC entry 5032 (class 2606 OID 49415)
-- Name: notes_note_tags notes_note_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_note_tags
    ADD CONSTRAINT notes_note_tags_pkey PRIMARY KEY (id);


--
-- TOC entry 5019 (class 2606 OID 49392)
-- Name: notes_tag notes_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_tag
    ADD CONSTRAINT notes_tag_pkey PRIMARY KEY (id);


--
-- TOC entry 5022 (class 2606 OID 49425)
-- Name: notes_tag notes_tag_user_id_name_e42e9eef_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_tag
    ADD CONSTRAINT notes_tag_user_id_name_e42e9eef_uniq UNIQUE (user_id, name);


--
-- TOC entry 5037 (class 2606 OID 49474)
-- Name: planner_task planner_task_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.planner_task
    ADD CONSTRAINT planner_task_pkey PRIMARY KEY (id);


--
-- TOC entry 5047 (class 2606 OID 49530)
-- Name: quizzes_flashcard quizzes_flashcard_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quizzes_flashcard
    ADD CONSTRAINT quizzes_flashcard_pkey PRIMARY KEY (id);


--
-- TOC entry 5044 (class 2606 OID 49516)
-- Name: quizzes_question quizzes_question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quizzes_question
    ADD CONSTRAINT quizzes_question_pkey PRIMARY KEY (id);


--
-- TOC entry 5040 (class 2606 OID 49502)
-- Name: quizzes_quiz quizzes_quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quizzes_quiz
    ADD CONSTRAINT quizzes_quiz_pkey PRIMARY KEY (id);


--
-- TOC entry 5054 (class 2606 OID 49543)
-- Name: quizzes_studysession quizzes_studysession_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quizzes_studysession
    ADD CONSTRAINT quizzes_studysession_pkey PRIMARY KEY (id);


--
-- TOC entry 5059 (class 2606 OID 49607)
-- Name: resources_resource resources_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resources_resource
    ADD CONSTRAINT resources_resource_pkey PRIMARY KEY (id);


--
-- TOC entry 5069 (class 1259 OID 54424)
-- Name: ai_assistan_user_id_2c29eb_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ai_assistan_user_id_2c29eb_idx ON public.ai_assistant_chatmessage USING btree (user_id, created_at);


--
-- TOC entry 5072 (class 1259 OID 54423)
-- Name: ai_assistant_chatmessage_user_id_2e30b8d4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ai_assistant_chatmessage_user_id_2e30b8d4 ON public.ai_assistant_chatmessage USING btree (user_id);


--
-- TOC entry 4977 (class 1259 OID 49370)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4982 (class 1259 OID 49281)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4985 (class 1259 OID 49282)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4972 (class 1259 OID 49267)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4993 (class 1259 OID 49297)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 4996 (class 1259 OID 49296)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 4999 (class 1259 OID 49311)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 5002 (class 1259 OID 49310)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4990 (class 1259 OID 49363)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 5065 (class 1259 OID 51507)
-- Name: dashboard_a_user_id_7f2c17_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dashboard_a_user_id_7f2c17_idx ON public.dashboard_activity USING btree (user_id, created_at DESC);


--
-- TOC entry 5068 (class 1259 OID 51506)
-- Name: dashboard_activity_user_id_75cecb87; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dashboard_activity_user_id_75cecb87 ON public.dashboard_activity USING btree (user_id);


--
-- TOC entry 5009 (class 1259 OID 49357)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 5012 (class 1259 OID 49358)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 5061 (class 1259 OID 49632)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 5064 (class 1259 OID 49631)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 5015 (class 1259 OID 49423)
-- Name: notes_category_user_id_b17705fe; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notes_category_user_id_b17705fe ON public.notes_category USING btree (user_id);


--
-- TOC entry 5023 (class 1259 OID 49442)
-- Name: notes_note_category_id_dfff76db; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notes_note_category_id_dfff76db ON public.notes_note USING btree (category_id);


--
-- TOC entry 5028 (class 1259 OID 49457)
-- Name: notes_note_tags_note_id_3c701a99; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notes_note_tags_note_id_3c701a99 ON public.notes_note_tags USING btree (note_id);


--
-- TOC entry 5033 (class 1259 OID 49458)
-- Name: notes_note_tags_tag_id_e3814610; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notes_note_tags_tag_id_e3814610 ON public.notes_note_tags USING btree (tag_id);


--
-- TOC entry 5026 (class 1259 OID 49443)
-- Name: notes_note_user_id_be6c80b4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notes_note_user_id_be6c80b4 ON public.notes_note USING btree (user_id);


--
-- TOC entry 5027 (class 1259 OID 49444)
-- Name: notes_note_user_id_d67ab6_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notes_note_user_id_d67ab6_idx ON public.notes_note USING btree (user_id, updated_at DESC);


--
-- TOC entry 5020 (class 1259 OID 49431)
-- Name: notes_tag_user_id_bddac101; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notes_tag_user_id_bddac101 ON public.notes_tag USING btree (user_id);


--
-- TOC entry 5034 (class 1259 OID 49487)
-- Name: planner_tas_user_id_df1184_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX planner_tas_user_id_df1184_idx ON public.planner_task USING btree (user_id, status, due_date);


--
-- TOC entry 5035 (class 1259 OID 49485)
-- Name: planner_task_category_id_6e2c80bc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX planner_task_category_id_6e2c80bc ON public.planner_task USING btree (category_id);


--
-- TOC entry 5038 (class 1259 OID 49486)
-- Name: planner_task_user_id_9361dd5c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX planner_task_user_id_9361dd5c ON public.planner_task USING btree (user_id);


--
-- TOC entry 5048 (class 1259 OID 49579)
-- Name: quizzes_flashcard_quiz_id_205457c3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quizzes_flashcard_quiz_id_205457c3 ON public.quizzes_flashcard USING btree (quiz_id);


--
-- TOC entry 5049 (class 1259 OID 49577)
-- Name: quizzes_flashcard_source_note_id_f73021ba; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quizzes_flashcard_source_note_id_f73021ba ON public.quizzes_flashcard USING btree (source_note_id);


--
-- TOC entry 5050 (class 1259 OID 49578)
-- Name: quizzes_flashcard_user_id_d321496c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quizzes_flashcard_user_id_d321496c ON public.quizzes_flashcard USING btree (user_id);


--
-- TOC entry 5045 (class 1259 OID 49561)
-- Name: quizzes_question_quiz_id_70961654; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quizzes_question_quiz_id_70961654 ON public.quizzes_question USING btree (quiz_id);


--
-- TOC entry 5041 (class 1259 OID 49554)
-- Name: quizzes_quiz_source_note_id_9c009e2e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quizzes_quiz_source_note_id_9c009e2e ON public.quizzes_quiz USING btree (source_note_id);


--
-- TOC entry 5042 (class 1259 OID 49555)
-- Name: quizzes_quiz_user_id_c5cc96af; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quizzes_quiz_user_id_c5cc96af ON public.quizzes_quiz USING btree (user_id);


--
-- TOC entry 5051 (class 1259 OID 49592)
-- Name: quizzes_stu_user_id_e1af82_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quizzes_stu_user_id_e1af82_idx ON public.quizzes_studysession USING btree (user_id, start_time DESC);


--
-- TOC entry 5052 (class 1259 OID 49590)
-- Name: quizzes_studysession_category_id_2c78bf08; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quizzes_studysession_category_id_2c78bf08 ON public.quizzes_studysession USING btree (category_id);


--
-- TOC entry 5055 (class 1259 OID 49591)
-- Name: quizzes_studysession_user_id_887d0c22; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quizzes_studysession_user_id_887d0c22 ON public.quizzes_studysession USING btree (user_id);


--
-- TOC entry 5056 (class 1259 OID 49620)
-- Name: resources_r_user_id_db7470_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX resources_r_user_id_db7470_idx ON public.resources_resource USING btree (user_id, resource_type);


--
-- TOC entry 5057 (class 1259 OID 49618)
-- Name: resources_resource_category_id_0cd2d52c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX resources_resource_category_id_0cd2d52c ON public.resources_resource USING btree (category_id);


--
-- TOC entry 5060 (class 1259 OID 49619)
-- Name: resources_resource_user_id_fde5fc52; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX resources_resource_user_id_fde5fc52 ON public.resources_resource USING btree (user_id);


--
-- TOC entry 5080 (class 2606 OID 49327)
-- Name: accounts_profile accounts_profile_user_id_49a85d32_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_49a85d32_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5102 (class 2606 OID 54418)
-- Name: ai_assistant_chatmessage ai_assistant_chatmessage_user_id_2e30b8d4_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_assistant_chatmessage
    ADD CONSTRAINT ai_assistant_chatmessage_user_id_2e30b8d4_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5074 (class 2606 OID 49276)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5075 (class 2606 OID 49271)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5073 (class 2606 OID 49262)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5076 (class 2606 OID 49291)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5077 (class 2606 OID 49286)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5078 (class 2606 OID 49305)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5079 (class 2606 OID 49300)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5101 (class 2606 OID 51501)
-- Name: dashboard_activity dashboard_activity_user_id_75cecb87_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dashboard_activity
    ADD CONSTRAINT dashboard_activity_user_id_75cecb87_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5081 (class 2606 OID 49347)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5082 (class 2606 OID 49352)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5083 (class 2606 OID 49418)
-- Name: notes_category notes_category_user_id_b17705fe_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_category
    ADD CONSTRAINT notes_category_user_id_b17705fe_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5085 (class 2606 OID 49432)
-- Name: notes_note notes_note_category_id_dfff76db_fk_notes_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_note
    ADD CONSTRAINT notes_note_category_id_dfff76db_fk_notes_category_id FOREIGN KEY (category_id) REFERENCES public.notes_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5087 (class 2606 OID 49447)
-- Name: notes_note_tags notes_note_tags_note_id_3c701a99_fk_notes_note_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_note_tags
    ADD CONSTRAINT notes_note_tags_note_id_3c701a99_fk_notes_note_id FOREIGN KEY (note_id) REFERENCES public.notes_note(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5088 (class 2606 OID 49452)
-- Name: notes_note_tags notes_note_tags_tag_id_e3814610_fk_notes_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_note_tags
    ADD CONSTRAINT notes_note_tags_tag_id_e3814610_fk_notes_tag_id FOREIGN KEY (tag_id) REFERENCES public.notes_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5086 (class 2606 OID 49437)
-- Name: notes_note notes_note_user_id_be6c80b4_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_note
    ADD CONSTRAINT notes_note_user_id_be6c80b4_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5084 (class 2606 OID 49426)
-- Name: notes_tag notes_tag_user_id_bddac101_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes_tag
    ADD CONSTRAINT notes_tag_user_id_bddac101_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5089 (class 2606 OID 49475)
-- Name: planner_task planner_task_category_id_6e2c80bc_fk_notes_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.planner_task
    ADD CONSTRAINT planner_task_category_id_6e2c80bc_fk_notes_category_id FOREIGN KEY (category_id) REFERENCES public.notes_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5090 (class 2606 OID 49480)
-- Name: planner_task planner_task_user_id_9361dd5c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.planner_task
    ADD CONSTRAINT planner_task_user_id_9361dd5c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5094 (class 2606 OID 49572)
-- Name: quizzes_flashcard quizzes_flashcard_quiz_id_205457c3_fk_quizzes_quiz_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quizzes_flashcard
    ADD CONSTRAINT quizzes_flashcard_quiz_id_205457c3_fk_quizzes_quiz_id FOREIGN KEY (quiz_id) REFERENCES public.quizzes_quiz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5095 (class 2606 OID 49562)
-- Name: quizzes_flashcard quizzes_flashcard_source_note_id_f73021ba_fk_notes_note_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quizzes_flashcard
    ADD CONSTRAINT quizzes_flashcard_source_note_id_f73021ba_fk_notes_note_id FOREIGN KEY (source_note_id) REFERENCES public.notes_note(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5096 (class 2606 OID 49567)
-- Name: quizzes_flashcard quizzes_flashcard_user_id_d321496c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quizzes_flashcard
    ADD CONSTRAINT quizzes_flashcard_user_id_d321496c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5093 (class 2606 OID 49556)
-- Name: quizzes_question quizzes_question_quiz_id_70961654_fk_quizzes_quiz_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quizzes_question
    ADD CONSTRAINT quizzes_question_quiz_id_70961654_fk_quizzes_quiz_id FOREIGN KEY (quiz_id) REFERENCES public.quizzes_quiz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5091 (class 2606 OID 49544)
-- Name: quizzes_quiz quizzes_quiz_source_note_id_9c009e2e_fk_notes_note_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quizzes_quiz
    ADD CONSTRAINT quizzes_quiz_source_note_id_9c009e2e_fk_notes_note_id FOREIGN KEY (source_note_id) REFERENCES public.notes_note(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5092 (class 2606 OID 49549)
-- Name: quizzes_quiz quizzes_quiz_user_id_c5cc96af_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quizzes_quiz
    ADD CONSTRAINT quizzes_quiz_user_id_c5cc96af_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5097 (class 2606 OID 49580)
-- Name: quizzes_studysession quizzes_studysession_category_id_2c78bf08_fk_notes_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quizzes_studysession
    ADD CONSTRAINT quizzes_studysession_category_id_2c78bf08_fk_notes_category_id FOREIGN KEY (category_id) REFERENCES public.notes_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5098 (class 2606 OID 49585)
-- Name: quizzes_studysession quizzes_studysession_user_id_887d0c22_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quizzes_studysession
    ADD CONSTRAINT quizzes_studysession_user_id_887d0c22_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5099 (class 2606 OID 49608)
-- Name: resources_resource resources_resource_category_id_0cd2d52c_fk_notes_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resources_resource
    ADD CONSTRAINT resources_resource_category_id_0cd2d52c_fk_notes_category_id FOREIGN KEY (category_id) REFERENCES public.notes_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5100 (class 2606 OID 49613)
-- Name: resources_resource resources_resource_user_id_fde5fc52_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resources_resource
    ADD CONSTRAINT resources_resource_user_id_fde5fc52_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-08-16 20:41:50

--
-- PostgreSQL database dump complete
--

\unrestrict QCZqeTnvYrBRmq8VAuvwOHf5Ry3fMlocDteLY3hcSRpcoMGZSh4igrnSexcCqja

